#### Ansible inventory.
resource "local_file" "ansible_inventory" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
all:
  hosts:
    db_host:
      ansible_host: "${data.ibm_is_instance.db-vsi.primary_network_interface[0].primary_ip[0].address}"
    DOC
  filename = "ansible/inventory.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "db_ansible_sapnwdb-vars" {
  depends_on = [ module.db-vsi ]
  content = <<-DOC
---
# Ansible vars_file containing variable values passed from Terraform.
# Generated by "terraform plan&apply" command.

# ASE SYB system configuration
db_host: "${module.db-vsi.PRIVATE-IP}"
db_hostname: "${trimspace(var.DB_HOSTNAME)}"
ase_sid: "${trimspace(var.ASE_SID)}"
ase_master_password: "${trimspace(var.ASE_MASTER_PASSWORD)}"
data_disk_size: "${trimspace(var.DATA_DISK_SIZE)}"
swap_disk_size: "${module.db-vsi.SWAP_DISK_SIZE}"

# ASE SYB Installation kit path
kit_ase_file: "${trimspace(var.KIT_ASE_FILE)}"

...
    DOC
  filename = "ansible/sapnwdb-vars.yml"
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_generated_file" {
  source = "${path.root}/modules/db-vsi/files/asesyb_vm_volume_layout.json"
  filename = "ansible/asesyb_vm_volume_layout.json"
}
